version: "2"
services:
  eurekaserver:
    image: polarcape/eurekaserver:1.0
    ports:
      - "8761:8761"
  configurationserver:
    image: polarcape/configurationserver:1.0
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY: "IMSYMMETRIC"
  zuulserver:
    image: polarcape/zuulserver:1.0
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configurationserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_PORT: "8888"
      EUREKASERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
  organizationservice1:
    image: polarcape/organizationservice:1.0
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configurationserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_PORT: "8888"
      EUREKASERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
  organizationservice2:
    image: polarcape/organizationservice:1.0
    ports:
      - "8086:8086"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8086"
      CONFIGSERVER_URI: "http://configurationserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_PORT: "8888"
      EUREKASERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
  licensingservice1:
    image: polarcape/licensingservice:1.0
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configurationserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_PORT: "8888"
      EUREKASERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
  licensingservice2:
    image: polarcape/licensingservice:1.0
    ports:
      - "8081:8081"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8081"
      CONFIGSERVER_URI: "http://configurationserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      CONFIGSERVER_PORT: "8888"
      EUREKASERVER_PORT: "8761"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB: "java_focus_group_demo"