server:
  port: 8888
spring:
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/KireP/java-focus-group-demo-config/
          searchPaths: licensingservice,organizationservice,zuulserver

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.polarcape: DEBUG