server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 30
  serviceUrl:
    defaultZone: http://localhost:8761

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.polarcape: DEBUG
